markdown: rdiscount
pygments: true
permalink: /:year/:month/:title

exclude: ['POST-IT.md', 'README.md']

lsi: true

name: Minni Blog
author: Benoit Charbonnier
url: http://blog.minni.im

disqus:
  short_name: roulotteblog
